name: complaint_portal
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  app_settings: ^4.2.0
  async_builder: ^1.3.1+1
  bottom_navy_bar: ^6.0.0
  cloud_firestore: ^4.4.5
  connectivity_plus: ^3.0.3
  cupertino_icons: null
  curved_navigation_bar: ^1.0.3
  custom_bottom_sheet: ^1.1.2
  date_format: ^2.0.7
  drop_down_list: ^0.0.4
  dropdown_button2: ^2.0.0
  equatable: ^2.0.5
  firebase_analytics: ^10.1.6
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  firebase_crashlytics: ^3.0.17
  firebase_messaging: null
  firebase_performance: ^0.9.0+16
  firebase_storage: ^11.0.16
  flutter:
    sdk: flutter
  flutter_form_builder: null
  flutter_launcher_icons: ^0.12.0
  flutter_local_notifications: ^13.0.0
  flutter_riverpod: null
  flutter_windowmanager: ^0.2.0
  font_awesome_flutter: null
  full_screen_image_null_safe: ^2.0.0
  fullscreen_window: ^1.0.4
  get: ^4.6.5
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  google_sign_in: null
  http: ^0.13.5
  image_picker: ^0.8.7
  intl: null
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  linkify: ^4.1.0
  location: ^4.4.0
  overlay_support: ^2.1.0
  permission_handler: ^10.2.0
  popup_banner: ^1.0.0
  provider: ^6.0.5
  recase: ^4.1.0
  regexpattern: null
  rxdart: null
  shared_preferences: null
  shared_preferences_riverpod: null
  sliding_up_panel: null
  url_launcher: null

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
