// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnu0IphtT5KcIco3AFRy4i54t3S4S40b4',
    appId: '1:591494154369:web:eb406ce80d7d24c71de580',
    messagingSenderId: '591494154369',
    projectId: 'complaint-portal-flutter',
    authDomain: 'complaint-portal-flutter.firebaseapp.com',
    databaseURL:
        'https://complaint-portal-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'complaint-portal-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaGqyFUhmAXKAClh8Hzv_08POYWEcav2I',
    appId: '1:591494154369:android:03ec6733745744cc1de580',
    messagingSenderId: '591494154369',
    projectId: 'complaint-portal-flutter',
    databaseURL:
        'https://complaint-portal-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'complaint-portal-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQF02ybPnDmvtLW1RTs2MJfkey-ev8Cls',
    appId: '1:591494154369:ios:3afedc6f6db0a1ce1de580',
    messagingSenderId: '591494154369',
    projectId: 'complaint-portal-flutter',
    databaseURL:
        'https://complaint-portal-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'complaint-portal-flutter.appspot.com',
    iosClientId:
        '591494154369-obcia02025js6ufqrpqi90pkr2pgo8cf.apps.googleusercontent.com',
    iosBundleId: 'com.example.complaintPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQF02ybPnDmvtLW1RTs2MJfkey-ev8Cls',
    appId: '1:591494154369:ios:3afedc6f6db0a1ce1de580',
    messagingSenderId: '591494154369',
    projectId: 'complaint-portal-flutter',
    databaseURL:
        'https://complaint-portal-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'complaint-portal-flutter.appspot.com',
    iosClientId:
        '591494154369-obcia02025js6ufqrpqi90pkr2pgo8cf.apps.googleusercontent.com',
    iosBundleId: 'com.example.complaintPortal',
  );
}
